name: Build, Push Docker Images and Update GitOps Repo

on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - frontend/**
      - .github/workflows/docker-publish.yml

env:
  BACKEND_IMAGE: kimhk1030/backend-app
  FRONTEND_IMAGE: kimhk1030/frontend-app
  GITOPS_REPO: kimhankyeol/myapp-gitops
  GITOPS_PATH: gitops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $BACKEND_IMAGE:latest \
            -f backend/Dockerfile \
            --push backend/

      - name: Build and push frontend image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $FRONTEND_IMAGE:latest \
            -f frontend/Dockerfile \
            --push frontend/

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO }}
          path: ${{ env.GITOPS_PATH }}
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update backend image tag in GitOps repo
        run: |
          cd $GITOPS_PATH/overlays/dev
          sed -i "s|image: .*|image: $BACKEND_IMAGE:latest|" patch-deployment-backend.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add patch-deployment-backend.yaml
          git commit -m "Update backend image tag to latest"
          git push

      - name: Update frontend image tag in GitOps repo
        run: |
          cd $GITOPS_PATH/overlays/dev
          sed -i "s|image: .*|image: $FRONTEND_IMAGE:latest|" patch-deployment-frontend.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add patch-deployment-frontend.yaml
          git commit -m "Update frontend image tag to latest"
          git push
