name: Build, Push Docker Image and Update GitOps Repo

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - app.py
      - requirements.txt
      - .github/workflows/docker-publish.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (multi-platform)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t kimhk1030/test-fast-api:latest --push .

      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: kimhankyeol/myapp-gitops
          path: gitops
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update image tag in GitOps repo
        run: |
          cd gitops/overlays/dev
          sed -i "s|image: .*|image: kimhk1030/test-fast-api:latest|" patch-deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add patch-deployment.yaml
          git commit -m "Update image tag to latest"
          git push
